# Generated by Django 6.0.2 on 2026-03-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
