# Generated by Django 6.0.2 on 2026-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Produto/Modelo')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial')),
                ('problem_description', models.TextField(verbose_name='Problema')),
                ('fix_action', models.TextField(blank=True, null=True, verbose_name='Correção')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CORRIGIDO', 'Corrigido'), ('CONDENADO', 'Condenado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('support_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
