# Generated by Django 6.0.2 on 2026-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttickets',
            name='client',
            field=models.CharField(default='', max_length=100, verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
