# Generated by Django 6.0.2 on 2026-03-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial')),
                ('mac_addres', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('client_name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('date_sent', models.DateField(verbose_name='Data de envio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.product')),
            ],
        ),
    ]
