# Generated by Django 6.0.2 on 2026-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreport',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Nota Ficasl (PDF)'),
        ),
    ]
