# Generated by Django 6.0.2 on 2026-03-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_name'),
        ('reports', '0002_dispatchreport_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchreport',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='inventory.product'),
        ),
    ]
